"use client";
import "../globals.css"
import "../data-tables-css.css";
import "../satoshi.css";
import { useState, useEffect } from "react";
import Loader from "@/components/shared/common/Loader";

import Sidebar from "@/components/shared/Sidebar";
import Header from "@/components/shared/Header";

// import LaboranSidebar from "@/components/(laboran)/Sidebar";
// import LaboranHeader from "@/components/(laboran)/Header";
import AdminHeader from "@/components/(superadmin)/Header";
// import { SidebarShadcn } from "@/components/(laboran)/sidebar-shadcn";
import { SidebarShadcn } from "@/components/(superadmin)/sidebar-shadcn";
import { SessionProvider } from "next-auth/react";

// import { Outlet } from 'next/navigation'; // Import Yang Benar 

export default function LaboranLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const [loading, setLoading] = useState<boolean>(true);
  
  const [isSheetOpen, setIsSheetOpen] = useState(false);
  const toggleSheet = () => setIsSheetOpen(!isSheetOpen);

  useEffect(() => {
    setTimeout(() => setLoading(false), 1000);
  }, []);

  return (
    <SessionProvider>
        <div className="">
          {loading ? (
            <Loader />
          ) : (
            <div className="flex h-screen overflow-hidden">
              {/* <!-- ===== Sidebar Start ===== --> */}
              {/* <LaboranSidebar
                sidebarOpen={sidebarOpen}
                setSidebarOpen={setSidebarOpen}
              /> */}
              <SidebarShadcn />
              {/* <!-- ===== Sidebar End ===== --> */}

              {/* <!-- ===== Content Area Start ===== --> */}
              <div className="relative flex flex-col flex-1 overflow-x-hidden overflow-y-auto bg-[#F1F5F9]">
                {/* <!-- ===== Header Start ===== --> */}
                {/* <LaboranHeader isSheetOpen={isSheetOpen} toggleSheet={toggleSheet} /> */}
                <AdminHeader
                  sidebarOpen={sidebarOpen}
                  setSidebarOpen={setSidebarOpen}
                />
                {/* <!-- ===== Header End ===== --> */}

                {/* <!-- ===== Main Content Start ===== --> */}
                <main>
                  <div className="p-4 mx-auto max-w-screen-2xl md:p-6 2xl:p-10 bg-[#F1F5F9]">
                    {children}
                    {/* <Outlet /> */}
                  </div>
                </main>
                {/* <!-- ===== Main Content End ===== --> */}
              </div>
              {/* <!-- ===== Content Area End ===== --> */}
            </div>
          )}
      </div>
    </SessionProvider>
  );
}


// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
