"use client";
import "../globals.css"
import "../data-tables-css.css";
import "../satoshi.css";
import { useState, useEffect } from "react";
import Loader from "@/components/shared/common/Loader";

// import Sidebar from "@/components/shared/Sidebar";
// import SidebarPraktikum from "@/components/(praktikum)/Sidebar";
// import Header from "@/components/shared/Header";

import PraktikumHeader from "@/components/(praktikum)/Header";
import { SidebarShadcn } from "@/components/(praktikum)/sidebar-shadcn";
import { SessionProvider } from "next-auth/react";
import { useSession } from "next-auth/react";
import { redirect, useRouter } from 'next/navigation';


export default function PraktikumLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    setTimeout(() => setLoading(false), 1000);
  }, []);

  const { data: session, status } = useSession();

  if (!session || (session.user.role !== "praktikum" && session.user.role !== "laboran")) {
    redirect("/login"); // Arahkan ke halaman login jika tidak ada sesi atau peran bukan "praktikum" atau "laboran"
  }


  return (
    // <html lang="en">
    //   <body suppressHydrationWarning={true}>
    <SessionProvider>
        <div className="">
          {loading ? (
            <Loader />
          ) : (
            <div className="flex h-screen overflow-hidden">
              {/* <!-- ===== Sidebar Start ===== --> */}
              {/* <SidebarPraktikum
                sidebarOpen={sidebarOpen}
                setSidebarOpen={setSidebarOpen}
              /> */}
              <SidebarShadcn />
              {/* <!-- ===== Sidebar End ===== --> */}

              {/* <!-- ===== Content Area Start ===== --> */}
              <div className="relative flex flex-col flex-1 overflow-x-hidden overflow-y-auto bg-[#F1F5F9]">
                {/* <!-- ===== Header Start ===== --> */}
                <PraktikumHeader
                  sidebarOpen={sidebarOpen}
                  setSidebarOpen={setSidebarOpen}
                />
                {/* <!-- ===== Header End ===== --> */}

                {/* <!-- ===== Main Content Start ===== --> */}
                <main>
                  <div className="p-4 mx-auto max-w-screen-2xl md:p-6 2xl:p-10 bg-[#F1F5F9]">
                    {children}
                  </div>
                </main>
                {/* <!-- ===== Main Content End ===== --> */}
              </div>
              {/* <!-- ===== Content Area End ===== --> */}
            </div>
          )}
        </div>
    </SessionProvider>
  );
}


// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
